### ISSUE TITLE
Kopirajto de la emblemo?

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/Tabuo#1]
Ĉu ni havas la kopirajton de la emblemoj? Mi dubas tion.

**Comment by georgjaehnig** [comment]
Do, mi volus publikigi la deponejon kaj la ludon sub libera permesilo (kiam Rob respondos). Tial ni bezonas klarecon pri la enhavoj kaj niaj rajtoj.

Bone, tiam mi forigos la emblemon. Dankon pri via rapida respondo! :)

**Comment by Timwi** [comment]
On 21/03/2016 01:53, Georg Jähnig wrote:

> Bone, tiam mi forigos la emblemon.

Eble mi devus atentigi al vi, ke kvankam vi forigis la png-dosierojn, 
tamen ankoraŭ kopio de la emblemo ekzistas enigita en la HTML kiel 
base64-kodado.

Timwi
