### ISSUE TITLE
Kreu retpaĝon por ludi Tabuon

### ISSUE THREAD

**Issue by georgjaehnig** [Esperanto/Tabuo#3]
Mi havis ideon de krei (komence) simplan retpaĝon kiu
- komence
  - enhavas ĉiujn divenendon en Javascript-tabelo (array)
  - ordigas ilin hazarde
- tiam montras unu divenendon kaj la tabuojn
- kaj havas "sekva" butonon.

Tiel oni povus ludi Tabuon sen printi la kartojn.

Tute devus ekzisti en unu simplan HTML-paĝon, tiel oni povus elŝuti ĝin kaj uzi senrete, ekz. en poŝtelefono.

Tiu estus la unua, plej facila versio. Poste oni povus pensi pri
- klikhorloĝon
- organizo de ludgrupoj kaj poentkalkulado.

Eble tiu tute ankaŭ pli bone estu alia program projekto "Taboo in Javascript" (kaj eble tio jam ekzistas).

**Comment by georgjaehnig** [comment]
Simpla estas jam farita jen:
http://tabuo.esperanto.com/

**Comment by djuretic** [comment]
Mojose! Dankon :+1:
